name: safehorizon
description: "Safe Horizon Accident Reporting App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ================= NETWORK / API =================
  http: ^1.6.0

  # ================= OPENSTREETMAP (OSM) =================
  # Replacing google_maps_flutter with flutter_map for zero-cost routing
  flutter_map: ^8.2.0  
  latlong2: ^0.9.1   # 🟢 Downgraded to 0.9.1 to fix version conflict

  # ================= LOCATION =================
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  # ================= VOICE ASSISTANT =================
  flutter_tts: ^3.8.5 # 🟢 Added for Text-to-Speech Navigation

  # ================= CAMERA / IMAGE =================
  image_picker: ^1.1.2

  # ================= DATE FORMAT =================
  intl: ^0.19.0

  # ================= LOCAL STORAGE =================
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png